### ISSUE TITLE
Meta: list of proposals we know we should have

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/proposals#2]
- [x] tags/overlays https://github.com/lbryio/proposals/issues/1
- [x] cross-device sync #11 
- [x] time to first byte https://github.com/lbryio/proposals/issues/3
- [ ] keyservers
- [ ] data payment
- [x] proof of purchase #6 #8 #9 #10 
- [ ] distributed reflectors (run by the community)
- [x] claim signatures / off-chain publishing https://github.com/lbryio/proposals/issues/5
